### ISSUE TITLE
你好，如果是在线加密mp3，也是这样的做法么？

### ISSUE THREAD

**Issue by dingdongnigetou** [ChangWeiBa/AesExoPlayer#2]
RT

**Comment by ChangWeiBa** [comment]
可以的，只要把uri的路径弄成可以识别的就行  比如： if (dataSpec.uri.getPath().endsWith(".aitrip"))

**Comment by dingdongnigetou** [comment]
谢回复，但有个疑问，如下代码
`  
            if (dataSpec.uri.getPath().endsWith(".aitrip")) {
                Aes128DataSource aes128DataSource =
                        new Aes128DataSource(getFileDataSource(), Aikey.getBytes(), Aikey.getBytes());
                dataSource = aes128DataSource;
            }
`
如果是基于http的mp3, 那这里应该不是getFileDataSource吧？

**Comment by ChangWeiBa** [comment]
应该是得换一个

**Comment by ChangWeiBa** [comment]
你去看看DefaultDataSource类头上面的注释：（http(s): For fetching data over HTTP and HTTPS (e.g. https://www.something.com/media.mp4), if constructed using {@link #DefaultDataSource(Context, TransferListener, String, boolean)}, or any other schemes supported by a base data source if constructed using {@link #DefaultDataSource(Context, TransferListener, DataSource)}.）



所以你应该可以使用DefaultDataSource来弄。

**Comment by ChangWeiBa** [comment]
DefaultDataSource类上面的说明，http(s): For fetching data over HTTP and HTTPS (e.g. https://www.something.com/media.mp4), if constructed using {@link #DefaultDataSource(Context, TransferListener, String, boolean)}, or any other schemes supported by a base data source if constructed using {@link #DefaultDataSource(Context, TransferListener, DataSource)}   那你使用DefaultDataSource(Context, TransferListener, String, boolean)试试？
